### ISSUE TITLE
S.N501 custom build: mask S.N501 just when building tree?

### ISSUE THREAD

**Issue by AngieHinrichs** [emmahodcroft/covariants#1]
Thank you for producing this totally awesome resource.  I know you're insanely busy so I don't expect a response, but just in case this is easily addressed -- in the [custom build for S.N501](https://nextstrain.org/groups/neherlab/ncov/S.N501?c=gt-S_501,69&r=country) tree, the S:N501Y/A23063T mutation appears to date to 2020-01-28, before the split between 20B and 20C, which would not be a good thing to take literally.  I imagine that's due to the sampling (mostly samples with S:N501 variants, although the actual frequency of those variants is <1% globally).  

Is there an easy way (or at least straightforward, or delegatable :) ) to mask S:N501 variants just when building the tree, and then to add them back in after the tree is built, to avoid 'warping' the tree like that?  If not, nm, better things to do.  :)

**Comment by emmahodcroft** [comment]
Hi @AngieHinrichs ! Thanks for the kind words! Yes, I really hope this useful.

Yes, thanks for spotting this. This is happening because of the number of sequences with the N501Y mutation vs those without - it's inferring that therefore it must be older, and the ones without are a back-mutation.  I'll have to have a bit of a think about how to address this - this is unfortunately not uncommon when dealing with these focal builds - as they're not at all random you can distort the trees. Gets worse when the focal mutation arises multiple times as the algorithms of course interpret that as being significant, when is rather, by design! 

I'll see if I can add some more 'non-501Y' sequences in the right place to force this back up... I'll see what I can do! But yes, can be hard to reliably 'trick' these algorithms sometimes...!

**Comment by AngieHinrichs** [comment]
Please don't waste too much time on this, especially the sampling part!  (Delegate?  Sorry I can't volunteer, if I had time I would just try it & send a pull request.)  I was just thinking that masking could be a reliable way to 'trick' it, or rather hide something that naturally confounds it.  ncov already [masks](https://github.com/nextstrain/ncov/blob/d6559b49999d70176d1bdecc59960ad4a04ecafb/defaults/parameters.yaml#L71) a few positions discovered early on to be lab-specific errors.  Rob Lanfear's [sarscov2phylo](https://github.com/roblanf/sarscov2phylo/) process [masks](https://github.com/roblanf/sarscov2phylo/blob/83e7e7eaf7ba521fe2a9222f3dd3dab16f1bb9d2/scripts/mask_alignment.sh#L32) a superset of those called "[Problematic Sites](https://github.com/W-L/ProblematicSites_SARS-CoV2)" because they're known to cause errors in phylogenies.  

I suspect the hard part (or new part, anyway) would be adding the variants of interest back in after the tree is constructed.

Hypothetically, if there existed a comprehensive augur v2 JSON blob with a giant tree of all samples, and then that were pruned down to include only your selected set of samples, would that serve the purposes of your custom build, or is there something that you get by doing a custom build that you would not get from pruning down from a big tree?

**Comment by emmahodcroft** [comment]
Oh dear - I didn't realise I'd never responded to this! So, I didn't end up trying to work in a mask at all, but I did update the runs to include more background, which seems to have solved this problem at least somewhat! 

You can see the new version here: https://nextstrain.org/groups/neherlab/ncov/S.N501?c=gt-S_501&p=grid&r=country

I still would not necessarily use it as the be-all-end-all for estimating when the mutation occurred (for one thing, the mutations on some of the long branches throw off our clock estimates), but at least now the mutations are not happening back before the 20-split! :) 

Thanks for spotting it, and sorry to take so long to write back, even after I fixed it!

**Comment by AngieHinrichs** [comment]
I saw you fixed it, no worries about writing back!  :)  Thanks!
